# Generated by Django 3.2.10 on 2022-02-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='admin_read',
        ),
        migrations.AddField(
            model_name='message',
            name='client_read',
            field=models.BooleanField(default=False),
        ),
    ]
