# Generated by Django 3.2.10 on 2022-02-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, upload_to='messages/'),
        ),
    ]
