# Generated by Django 3.2.10 on 2022-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220306_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Addis Ababa', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special_name',
            field=models.CharField(blank=True, default='bole-bulbula', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_city',
            field=models.CharField(blank=True, default='bole', max_length=50),
        ),
    ]
