# Generated by Django 3.2.10 on 2022-04-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220312_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='09xxxxxxxx', max_length=15),
        ),
    ]
