# Generated by Django 3.2.10 on 2022-04-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220404_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='special_name',
        ),
    ]
