# Generated by Django 3.2.10 on 2022-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_sample'),
        ('accounts', '0006_remove_profile_special_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='read',
            field=models.ManyToManyField(related_name='read', to='blog.Post'),
        ),
    ]
