# Generated by Django 3.2.10 on 2022-02-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_youtubeplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narration',
            name='audio',
            field=models.FileField(upload_to='narrations/'),
        ),
    ]
