# Generated by Django 3.2.10 on 2022-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
