# Generated by Django 3.2.10 on 2022-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_reads'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sample',
            field=models.TextField(blank=True),
        ),
    ]
