# Generated by Django 3.2.10 on 2022-04-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_release_release'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Release',
        ),
    ]
